### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by akatav** [nyukat/breast_cancer_classifier#1]
Hi
Nice library! Will i need GPU to run this on? Can you perhaps add a readme to run this on gcloud (which i suppose already has supporch for pytorch and gpu).

Thanks
Supraja

**Comment by jpatrickpark** [comment]
Hi, 

While we recommend using GPU, it is possible to run our model entirely on CPU. Please set DEVICE_TYPE='cpu' in line 4 of run.sh before running it.

We currently do not plan on including instructions for how to run our models on gcloud.

Best,
JP
