### ISSUE TITLE
How long did it take to complete the Stage 3 (Generate Heatmaps) ? 

### ISSUE THREAD

**Issue by eastchun** [nyukat/breast_cancer_classifier#10]
I am running your codes in 'cpu' environment. 
It is extremely slow.
How long did it take to complete the Stage 3 (for your 4 sample images) in a single GPU environment?

**Comment by jpatrickpark** [comment]
Hi,

With a GPU, it took me about 2 minutes to complete Stage 3 with 4 provided exams.

**Comment by eastchun** [comment]
Thanks, looks like a local problem in my laptop.
