### ISSUE TITLE
Question on your patch classifier.

### ISSUE THREAD

**Issue by eastchun** [nyukat/breast_cancer_classifier#11]
I have a question about your patch classifier.
In your scripts, number_of_classes of your patch_classifier (DenseNet121) is specified by 4.

Question 1. Do these 4 classes mean : no_benign, benign, no_malignant, malignant ?

Question 2. Is the configuration of the output stage in your patch classifier something like:
                   AvePool2D (7x7x1024,, sirides=1x1) --> linear(1000) --> softmax (4) ???

**Comment by wooginawunan** [comment]
Question 1. Do these 4 classes mean : no_benign, benign, no_malignant, malignant ?

You could find more details about the patch classifier in our appendix. The four classes are malignant, benign, outside and negative. 
- malignant: patches with overlap with only malignant biopsy annotation. 
- benign: patches with overlap with only benign biopsy annotation. 
- outside: patches cropped from images matched with biopsy record, but without overlap with any annotation. 
- negative: patches cropped from images which do not matched with any biopsy records.

Question 2. Is the configuration of the output stage in your patch classifier something like:
AvePool2D (7x7x1024,, sirides=1x1) --> linear(1000) --> softmax (4) ???

There is only one linear layer in the end, which we directly modify the number of neurons to 4. So following your annotation it is like:

AvePool2D (7x7x1024,, sirides=1x1) --> linear(4) --> softmax
