### ISSUE TITLE
missing single_image files

### ISSUE THREAD

**Issue by saraEbrahim** [nyukat/breast_cancer_classifier#14]
Hi,
Is it intended or these files are just missing? they were mentioned in the newly uploaded notebook:
sample_single_output/cropped.png
sample_single_output/cropped_metadata.pkl

**Comment by jpatrickpark** [comment]
Hi,

As indicated in the notebook, we expect that the preprocessing (e.g. cropping) have been completed beforehand by executing the following command found in the README file:

`bash run_single.sh "sample_data/images/0_L_CC.png" "L-CC"`

This command generates the necessary image files required by the notebook.
