### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by saraEbrahim** [nyukat/breast_cancer_classifier#18]
If I have dataset that dont have the 4 views of a test, how would I benefit from NYU model and fine tune it?

can I run the same image over the 4 views or the 2 views in the single_image model and take the average? 

and why there are Right and Left while the preprocessing flips all images to be Left?

**Comment by zphang** [comment]
In our 4-view model, we take left and right MLO/CC views as inputs. However, when we apply the model, we flip the images as necessary so they are all aligned in the same manner.

For your use case, you should be able the use the image-wise model: https://github.com/nyukat/breast_cancer_classifier#single-image

**Comment by saraEbrahim** [comment]
I have all the mammograms as (Left), should I use the L-CC and L-MLO models and average the results or try each one separately?

**Comment by zphang** [comment]
Both should work. We find that ensembling often helps.
