### ISSUE TITLE
View the original image with heatmaps

### ISSUE THREAD

**Issue by estimoelmo** [nyukat/breast_cancer_classifier#2]
Hi, 

Thanks for the great contribution in mammogram! I really appreciate your work. I just wonder, how to view the heatmap prediction to the original image?

Ive tried to view the hdf5 file but didnt get quite right for this.

Thanks!

**Comment by jpatrickpark** [comment]
Hi,

Please use the `load_image` function in ` src/data_loading/loading.py` to load either png or hdf5 files using appropriate view and horizontal_flip information. Alternatively, you can use `read_image_mat` in `src/utilities/reading_images.py` to load the hdf5 heatmaps without view and horizontal_flip information.

It will be loaded as a numpy array, which can be plotted as follows:

```python
import matplotlib.pyplot as plt
from src.utilities.reading_images import read_image_mat

image = read_image_mat(image_path)
plt.imshow(image)
plt.show()
```

**Comment by tahavarol** [comment]
Hello, when I am trying to plot hdf5 file the image look very bad. I have used **read_image_mat** function. Where do I am doing the mistake. Thanks in advance.

**Comment by jpatrickpark** [comment]
Could you clarify what you mean by that? Do you mean the image looks corrupted?

**Comment by tahavarol** [comment]
As I understood, hdf5 file contains heat map only, to generate a full image just like in your paper, we have to overlay the original image with heat map. However, the heat map is quite pixelated. And I got only green tones which I think no malignancy detected. Am I applying the right method to obtain the images like in the paper? Thank you :)

**Comment by Emirbz** [comment]
Hello , can i save the hdf5 heatmaps to png file ?

**Comment by wooginawunan** [comment]
Sure. You could save the heat maps as png files. The generated heat maps are just numpy arrays with value between 0-1. You use 'scipy.misc.imsave' to save it as png file but just be careful while loading those png files especially if you still want to take them as input the following models. Values might be transformed to fit the typical png image scale (0-255).

**Comment by Tonthatj** [comment]
Very low res heatmap, is there anyway to clean it up? already saved as png.

**Comment by kjgeras** [comment]
@Tonthatj The heatmap is supposed to be of lower resolution than the original image. Note that the classifier is applied with a stride much bigger than 1.
