### ISSUE TITLE
Working with my own images

### ISSUE THREAD

**Issue by jeromejarre** [nyukat/breast_cancer_classifier#20]
Hi, I am trying to produce a result from your single image model. However, when I try to use my own DICOM images, my images are failed when it comes to use your cropping script. The cropped output is the same as the 16 bit png input. And also, when I tried to load it into the model to make an inference, I just saw almost fully black image when I wanted to try visualizing the tensor batch. Long story short, I cannot obtain a consistent raw image, cropped image and a tensor batch trio. I am working with uint16 image data. What can be the reason for this? Many thanks.
Kindest regards.

**Comment by jeromejarre** [comment]
Interestingly, I can make an inference using uint8 images.

**Comment by kjgeras** [comment]
Hi,

My guess is that your images have some artifact (e.g. a white frame around the image) that is preventing the cropping algorithm from working. You should investigate this kind of things by checking carefully what our cropping code is executing step by step. You should also read this report https://cs.nyu.edu/~kgeras/reports/datav1.0.pdf for details on what data we rejected and our cropping algorithm won't work with. 

It doesn't sound like anything related to the model itself.

**Comment by jeromejarre** [comment]
Big thanks, Professor Geras. Admired your and your team's work. Inspirational.
