### ISSUE TITLE
Train model on other radiography dataset

### ISSUE THREAD

**Issue by DhruvGamdha** [nyukat/breast_cancer_classifier#21]
Is there some way to train this model on other radiography dataset? The dataset I am dealing with is the X-ray of casting and weld of mechanical components in which I want to detect and classify defects.

**Comment by kjgeras** [comment]
You can definitely use this network as a starting point and retrain it on your task. In that case you should probably use the version that doesn't use heatmaps and takes one image at a time. Whether it will work better than transferring from a network trained on ImageNet or some other large data set depends on the charactersitics of your data and it's hard to guess.

If you try using our network, let us know!
