### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by parkhojun** [nyukat/breast_cancer_classifier#23]
python3 src/cropping/crop_mammogram.py \
    --input-data-folder $DATA_FOLDER \
    --output-data-folder $CROPPED_IMAGE_PATH \
    --exam-list-path $INITIAL_EXAM_LIST_PATH  \
    --cropped-exam-list-path $CROPPED_EXAM_LIST_PATH  \
    --num-processes $NUM_PROCESSES

Hi when i try to execute the this, I got the following error. Can you help me please? Thanks :)

Traceback (most recent call last):
  File "src/cropping/crop_mammogram.py", line 32, in <module>
    import src.utilities.pickling as pickling
ModuleNotFoundError: No module named 'src'

**Comment by LubomirKovalcik** [comment]
How did you fix it?

**Comment by Amanikl** [comment]
How can i fix this error ?
