### ISSUE TITLE
KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by ankitdata** [nyukat/breast_cancer_classifier#25]
getting above ERROR during stage 3 run.
after research discovered that torch vision package needs to be updated to 0.2.1 (https://github.com/pytorch/vision/pull/474)
this is just an FYI

**Comment by zphang** [comment]
Hi @ankitdata,

Is it the opposite issue? The models are not compatible with a newer torchvision version that has more restrictions on module keys. I tested the setup on a fresh install using the existing requirements and it works fine with the currently specified versions of PyTorch and torchvision.
