### ISSUE TITLE
random number generator on len(datum[view])

### ISSUE THREAD

**Issue by jamesjjcondon** [nyukat/breast_cancer_classifier#26]
Hi, 

Thanks so much for this repo. Great stuff. And love the paper.

the len(datum[view]) from [here](https://github.com/nyukat/breast_cancer_classifier/blob/master/src/modeling/run_model.py#L104) seems to consistently be 1. And then the image_index is always zero.

Is that right?

Thanks again.

**Comment by jpatrickpark** [comment]
That is the case for the examples included in this repository. They happened to have only one image per view. The randomization will work as expected when an exam with more than one image per view is provided (e.g. an exam which has two different images for L-CC view).
