### ISSUE TITLE
Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence

### ISSUE THREAD

**Issue by LubomirKovalcik** [nyukat/breast_cancer_classifier#27]
Stage 1: Crop Mammograms
sample_data/images\0_L_CC.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\0_R_CC.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\1_L_MLO.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\1_R_MLO.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\1_R_CC.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\1_L_CC.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\0_L_MLO.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
sample_data/images\0_R_MLO.png
        Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Lubomir\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Lubomir\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\Lubomir\Downloads\breast_cancer_classifier-master\breast_cancer_classifier-master\src\cropping\crop_mammogram.py", line 351, in crop_mammogram_one_image_short_path
    return list(zip([scan['short_file_path']] * 4, cropping_info))
TypeError: 'NoneType' object is not iterable
"""

Hello,

 I tried to run it with custom data set, but I keep getting this error:
        **Failed to crop image because image is invalid. attempt to get argmax ofan empty sequence**

0 and 1 are all images converted from DICOM to PNG and then cropped to: 2290 × 1890 pixels.

It seems like it is not working just with my images added to dataset.

**Comment by kjgeras** [comment]
I don't think this error is related in any way to your images. It just looks like the list of images you created is in a format that is not compatible with our code. Look again at our list and then at your list and you will likely easily find a bug. Note that the error at the bottom is "TypeError: 'NoneType' object is not iterable" when you are trying to execute 

`return list(zip([scan['short_file_path']] * 4, cropping_info))`
