### ISSUE TITLE
prediction of a single case

### ISSUE THREAD

**Issue by Emirbz** [nyukat/breast_cancer_classifier#3]
Thanks for the great contribution in mammogram! I really appreciate your work.I'm using this repository for my school project but i just wonder, how to use the project to predict one single case (4 mammogram photos) instead of  16 (16 photos found in sample_data/images).
i tried many things before asking and did not work , it keeps asking for the rest of images , or batch_size error

Thanks for reading my question

**Comment by banyet1** [comment]
Edit sample_data/exam_list_before_cropping.pkl,  remove the contents u don't need.

**Comment by zphang** [comment]
As mentioned by @banyet1, modifying `sample_data/exam_list_before_cropping.pkl` accordingly should solve the problem. That file contains the metadata data for the exams to process, and is used at the start of the processing pipeline.

**Comment by parkhojun** [comment]
I want to see example modifying sample_data/exam_list_before_cropping.pkl

**Comment by jpatrickpark** [comment]
@parkhojun The following is an example of creating a new exam list file which contains the first exam from `sample_data/exam_list_before_cropping.pkl`.
```python
import src.utilities.pickling as pickling
exam_list = pickling.unpickle_from_file('sample_data/exam_list_before_cropping.pkl')
custom_exam_list = [exam_list[0]]
pickling.pickle_to_file('custom_exam_list_before_cropping.pkl', custom_exam_list)
```

The content of `exam_list` variable is as follows:
```python
[{'horizontal_flip': 'NO',
  'L-CC': ['0_L_CC'],
  'L-MLO': ['0_L_MLO'],
  'R-MLO': ['0_R_MLO'],
  'R-CC': ['0_R_CC']},
 {'horizontal_flip': 'NO',
  'L-CC': ['1_L_CC'],
  'R-MLO': ['1_R_MLO'],
  'L-MLO': ['1_L_MLO'],
  'R-CC': ['1_R_CC']},
 {'horizontal_flip': 'NO',
  'R-MLO': ['2_R_MLO'],
  'L-MLO': ['2_L_MLO'],
  'L-CC': ['2_L_CC'],
  'R-CC': ['2_R_CC']},
 {'horizontal_flip': 'NO',
  'L-CC': ['3_L_CC'],
  'R-CC': ['3_R_CC'],
  'L-MLO': ['3_L_MLO'],
  'R-MLO': ['3_R_MLO']}]
```

The content of `custom_exam_list` variable is as follows:
```python
[{'horizontal_flip': 'NO',
 'L-CC': ['0_L_CC'],
 'L-MLO': ['0_L_MLO'],
 'R-MLO': ['0_R_MLO'],
 'R-CC': ['0_R_CC']}]
```

**Comment by parkhojun** [comment]
Thank you for your answer, and where can we find more sample images that can be used for that code?

**Comment by jpatrickpark** [comment]
@parkhojun You may want to look for public datasets such as CBIS-DDSM.
