### ISSUE TITLE
train our own data without 4 views

### ISSUE THREAD

**Issue by picEmily** [nyukat/breast_cancer_classifier#30]
our data do not have 4 standard views. how should I train own data？

**Comment by wooginawunan** [comment]
Hi, we provide a model suitable for single images: [(https://github.com/nyukat/breast_cancer_classifier/blob/7c8ceb6e28c1b60162830958d0429915d3010775/src/modeling/models.py#L116)]
and you can take the script [https://github.com/nyukat/breast_cancer_classifier/blob/master/src/modeling/run_model_single.py] and to build a training script based on it.
