### ISSUE TITLE
unable to read HDF5 files benign and malignant

### ISSUE THREAD

**Issue by ankitdata** [nyukat/breast_cancer_classifier#31]
I used given sample images and ran run.sh all of the steps successfully completed. but i am unable to read hdf5 files from heatmaps benign and malignant.

I used tools like below to convert them to png 
hdf5 viewer
https://mygeodata.cloud/converter/hdf5-to-png

any recommendations on how to read these HDF5 files ?

**Comment by kjgeras** [comment]
Please read this file
https://github.com/nyukat/breast_cancer_classifier/blob/master/src/data_loading/loading.py
