### ISSUE TITLE
Question on when to use models in practical settings

### ISSUE THREAD

**Issue by anguyen8** [nyukat/breast_cancer_classifier#36]
Dear authors,

Thanks so much for releasing this very useful code!

I have a related question that I hope to hear from you:
I am assuming that radiologists or healthcare workers at NYU are using your models.

How do you determine when the models are good enough for practical use?
Is it all up to a particular clinical standard? OR is there a set of general standards somewhere?

Any pointers would be much appreciated!!

Anh

**Comment by kjgeras** [comment]
Hi Anh! I will answer to your email.
