### ISSUE TITLE
Official request of the dataset

### ISSUE THREAD

**Issue by GKalliatakis** [nyukat/breast_cancer_classifier#38]
Hi, I wanted to know whether the dataset has been made public. 

If not, is there a way I can formally request to have access to the data under the regulations of your organisation or else if you are planning to release it in future.

**Comment by kjgeras** [comment]
Hi Gregorios,

It's not public and I can't currently promise anything about whether it
will in the future. There might be however some alternative ways we could
collaborate.

Please write me an email: k.j.geras@nyu.edu explaining what you would like
to do, how and why.
