### ISSUE TITLE
Resize transform for images during training

### ISSUE THREAD

**Issue by monkeysforever** [nyukat/breast_cancer_classifier#39]
Apart from being cropped was any explicit resize applied to the images? I am trying to fine-tune on the DDSM dataset and noticed varying performance on different resize values. Thanks for sharing model weights.

**Comment by wooginawunan** [comment]
Hi, before cropping, we did not apply any explicit resizing operations on the image. As mentioned in the SI of the paper, during training and test, the data augmentation operations we considered include slightly modifying the crop window size (maximum diff within 100 pixels) and resizing using bicubic interpolation to fit the desired size for the model.
