### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by Klonoaa** [nyukat/breast_cancer_classifier#40]
I have problems in the preprocessing fase when I run the code on Jupyter.
Infact when I run the following part gives me this error:

model_input = load_inputs(
    image_path="sample_single_output/cropped.png",
    metadata_path="sample_single_output/cropped_metadata.pkl",
    use_heatmaps=False,
)

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-53-f6c91cdb0096> in <module>
      2     image_path="sample_single_output/cropped.png",
      3     metadata_path="sample_single_output/cropped_metadata.pkl",
----> 4     use_heatmaps=False,

**Comment by wooginawunan** [comment]
Hi, based on your comment, I would suggest that you check whether you have added the path to python. For example, "sys.path.append('the folder include sample_single_output ')"
