### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Mohammed91** [nyukat/breast_cancer_classifier#43]
Is this dataset publicly available? where is the download link ?

**Comment by kjgeras** [comment]
It is not.

**Comment by kanishksh4rma** [comment]
> Is this dataset publicly available? where is the download link ?

You have to make a request on their website. Write a short note like - I want to make a project so pls provide me the dataset. Then they will send you the dataset link on ur mail 📂 hope this help 👍
