### ISSUE TITLE
Permission to release my PyTorch implementation for the training procedure and the dataset implementation 

### ISSUE THREAD

**Issue by MohammedAlkhrashi** [nyukat/breast_cancer_classifier#49]
Hi everyone, I highly appreciate the work you put into this fantastic paper in the field of breast cancer classification. 

I've noticed that this code doesn't include the code for the training procedure, so, I've implemented my own custom training procedure, and a dataset implementation (Pytorch's dataset class). 

I wanted to release my implementation for others to use in the future, and I just wanted to make sure that this is fine by the NYU team.

**Comment by kjgeras** [comment]
Hi Mohammed,

I think you are completely free to do that. The only think that you should careful about is releasing your code with the right license. I believe the easiest thing for you to do would be to release your code with the AGPLv3 license. However, please read our license before you make a decision that: https://github.com/nyukat/breast_cancer_classifier/blob/master/LICENSE

Best,
Krzysztof

**Comment by MohammedAlkhrashi** [comment]
Very well, thank you!

**Comment by bhosalems** [comment]
Hey, @MohammedAlkhrashi may I know the repo name for the same? I am currently comparing the results in this domain and would want to reproduce the results with multiple datasets.
