### ISSUE TITLE
Weights Resnet 22

### ISSUE THREAD

**Issue by frankissimo** [nyukat/breast_cancer_classifier#51]
Is it possible to share the original weights of the pre-trained resnet22?

**Comment by githubFrandeveloperb354** [comment]
> Is it possible to share the original weights of the pre-trained resnet22?

**Comment by kjgeras** [comment]
Hi Frankissimo,

We didn't use ImageNet to pretrain the ResNet-22. If you are talking about BI-RADS pretrained weights I am afraid we don't have them stored any more.

**Comment by githubFrandeveloperb354** [comment]
Do you have a reference from which I can download them?

**Comment by frankissimo** [comment]
Do you have a reference from which I can download them?
