### ISSUE TITLE
question about model

### ISSUE THREAD

**Issue by tks1998** [nyukat/breast_cancer_classifier#54]
Why you classification only 3 class (incomplete, normal, benign) ? why not included malignant class ?

**Comment by wooginawunan** [comment]
Hi, could you point me to where do you find the 3 classes as you listed in the question? We train our model for two binary classification tasks about benign and malignant finding prediction as stated in the Readme.

**Comment by tks1998** [comment]
In pretrain bi-rads classification chapter, the paper mentioned classification 3 classes: 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/37293650/160323112-723a37ae-06af-4f9c-9375-82534008b42c.png">

**Comment by kjgeras** [comment]
This is pretraining. In the fine-tuning phase we use the benign class. Please read the paper carefully and you will find a detailed description of how everything is done.
