### ISSUE TITLE
How to create a new exam list ?

### ISSUE THREAD

**Issue by bhosalems** [nyukat/breast_cancer_classifier#55]
Hi, Thanks for sharing your code!

Is there any utility to create the exam list in the format needed for this code from standard mammography datasets such as DDSM, INBREAST ?

**Comment by kjgeras** [comment]
We have already done this. Please look here: https://github.com/nyukat/mammography_metarepository

**Comment by bhosalems** [comment]
I checked the GitHub repo, but could not find the code to create a new data list pickle file.

**Comment by kjgeras** [comment]
Please read the paper about the metarepository you will have an answer to your question: https://arxiv.org/abs/2108.04800
